Newsweek clone
Hermela-Fikre/Newsweek pull request #1
Opened 2020-03-23 14:13 UTC by Hermela-Fikre

In this project:

- I used bootstrap.
- I used Html validation and stickler to enhance the code.

2020-03-23 14:57 UTC, mikenath223 commented
Pull request currently under review by Michgolden Ukeje (TSE)
Kindly exercise patience. 🐱

2020-03-23 16:17 UTC, mikenath223 requested changes
### Well done @Hermela-Fikre 👏👏

You've done quite well on this. 👍

However, there are a few minor changes I trust you will make before moving forward.
They are outlined below.

Good job once more. 👌

- [ ] _REQUIRED_ Make top-bar navigation links clickable. This includes the Sign-In/Subscribe element.
![header-review](https://user-images.githubusercontent.com/33323077/77336540-f3396b00-6d27-11ea-8bd4-43ee88aba02d.png)

- [ ] OPTIONAL Add more margin to bottom footer.
![footer](https://user-images.githubusercontent.com/33323077/77337346-10226e00-6d29-11ea-81af-3b17b476e410.png)

- [ ] _REQUIRED_ Remove comments in code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)).

2020-03-23 16:19 UTC, mikenath223 commented on style.css
> +} */
Kindly remove these comments.

2020-03-23 16:20 UTC, mikenath223 commented on index.html
> +                    <div class="col-md-5 order-md-0"> <!-- Col 1 -->
Kindly remove the comment: <!-- Col 1 -->

2020-03-23 16:21 UTC, mikenath223 commented on index.html
> +                    <div class="col-md-7 col-lg-7 d-flex flex-column"> <!-- Col 2-->
Kindly remove the comment: <!-- Col 2 -->

2020-03-24 07:45 UTC, MarioDena approved these changes
Hello great work on making the requested changes! 👍 

## Your project is approved! 🏅 

## Optional changes

- [ ] There are some repeated rules on your CSS for example some `color` rules, this is generally a mandatory requirement but I'm listing it as optional since it was not mentioned on your previous review. This change is [OPTIONAL]

However I really recommend you make a review of your CSS since it will be mandatory on future projects. Here is an article if you need further help.  https://speckyboy.com/good-bad-css-practices/

Cheers!

## Code review by Mario Enrique Delgado Naranjo

2020-03-24 07:56 UTC, merged